// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdGURbtT0dt1VC9wxQiY2jfYFIaKN_CXU',
    appId: '1:534597684157:web:98e3250d2d8c939d1aa0d4',
    messagingSenderId: '534597684157',
    projectId: 'myportfolio-amangupta',
    authDomain: 'myportfolio-amangupta.firebaseapp.com',
    storageBucket: 'myportfolio-amangupta.appspot.com',
    measurementId: 'G-NKEYD68RJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeBL9_H8XJp8UxNjH3yF4RHRpEaqNpdW0',
    appId: '1:534597684157:android:41f99fb2adbc8f3b1aa0d4',
    messagingSenderId: '534597684157',
    projectId: 'myportfolio-amangupta',
    storageBucket: 'myportfolio-amangupta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUI_q0iZJOBennTkA_Cn4oQWSLalRmJQ',
    appId: '1:534597684157:ios:e85ff61e099ff2c81aa0d4',
    messagingSenderId: '534597684157',
    projectId: 'myportfolio-amangupta',
    storageBucket: 'myportfolio-amangupta.appspot.com',
    iosBundleId: 'dev.dileepabandara.dileepabandaraDev',
  );
}
